### ISSUE TITLE
Came across this new list

### ISSUE THREAD

**Issue by nycnewman** [mallorybowes/chrome-mal-ids#12]
https://threatit.com/articles/28-dangerous-extensions-detected-for-google-chrome-and-microsoft-edge/?fbclid=IwAR1UTc6Zqwl7tl7NVVTXuDvuUoEdGUDnIUzc_oGmBGma2wTQjgkIaodapIk

**Comment by mallorybowes** [comment]
Thanks! I saw the Google alert hit my inbox this morning but haven't got to the computer yet today. Heading there now to update and thanks again for the catch!

--mal.

-------- Original Message --------

**Comment by mallorybowes** [comment]
I updated the list of extensions and after a few times trying to remember how to format basic HTML, :-/ I got the changes pushed.  Thanks again for the head's up and I'll close this issue!
